// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByU3wocGH7WgkwrKzJBProq2m4DRfvkaE',
    appId: '1:495227019162:web:18965417c244662a05a423',
    messagingSenderId: '495227019162',
    projectId: 'mash-90702',
    authDomain: 'mash-90702.firebaseapp.com',
    storageBucket: 'mash-90702.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzM2t_uRHXA-ZjnvmX_j6CjgR6-y4Lqbk',
    appId: '1:495227019162:android:0146956d4635288005a423',
    messagingSenderId: '495227019162',
    projectId: 'mash-90702',
    storageBucket: 'mash-90702.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPYrjvEO-kbiRqU-rBodoP2X168IVGYGU',
    appId: '1:495227019162:ios:39b8a9c467bac8dd05a423',
    messagingSenderId: '495227019162',
    projectId: 'mash-90702',
    storageBucket: 'mash-90702.appspot.com',
    iosBundleId: 'com.example.mash',
  );
}
